server:
  port: 8081

spring:
  kafka:
#    bootstrap-servers: b-1.ssp2pilotmskclust.1uyf1j.c3.kafka.ap-northeast-2.amazonaws.com:9096,b-2.ssp2pilotmskclust.1uyf1j.c3.kafka.ap-northeast-2.amazonaws.com:9096
#    bootstrap-servers: localhost:9092
#    bootstrap-servers: kafka1:19092,kafka2:29092,kafka3:39092
    bootstrap-servers: 100.64.106.137:9096
